eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: person
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show_sql: true
  datasource:
    url: jdbc:mysql://localhost:4306/itp
    username: itp
    password: itp
server:
  port: 8200




